require('plugins')
require('settings')

require('keybinding')
require('colorscheme')
require('highlight')

require("plugins.tresitter")
require("plugins.telescope")
require("plugins.compe")
require("plugins.gitsigns")
require("plugins.colorizer")
require("plugins.lualine")
require("plugins.nvimtree")
require("plugins.spectre")
require("plugins.tmux")
require("plugins.misc")
require("plugins.lightspeed")
require("plugins.terminal")
require("plugins.harpoon")
require("plugins.autosave")
require("plugins.zenmode")

require('lsp/config')
require('lsp/efm')
require('lsp/tsserver')
require('lsp/cssls')

